name: mesh_gradient
description: Widgets which create beautiful fluid-like mesh gradients in Flutter.
version: 1.3.5
repository: https://github.com/ben-fornefeld/mesh_gradient

screenshots:
  - description: "Animated Mesh Gradient"
    path: example/demo/demo-animated.webp

topics:
  - flutter
  - gradient
  - mesh
  - animation
  - ui

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <4.0.0"

flutter:
  shaders:
    - packages/mesh_gradient/shaders/animated_mesh_gradient.frag
    - packages/mesh_gradient/shaders/point_mesh_gradient.frag

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:
